version: '3.8'
services:
   web:
      image: mariadziuba/lab3_bd:latest
      ports:
        - 8001:8001
      env_file:
        - .env
      depends_on:
        - clickhouse
       
   clickhouse:
      image: clickhouse/clickhouse-server
      ports:
        - 9000:9000
        - 8123:8123
        - 9009:9009
      environment:
        - CLICKHOUSE_USER=${CLICKHOUSE_LOGIN}
        - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PWD}